import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { BeerProvider } from "@/context/beer";
import { ModalProvider } from "@/context/modal";
import StyledComponentsRegistry from "@/lib/registry";
import Theme from "@/lib/theme";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <StyledComponentsRegistry>
            <BeerProvider>
              <ModalProvider>
                <main>{children}</main>
              </ModalProvider>
            </BeerProvider>
          </StyledComponentsRegistry>
        </Theme>
      </body>
    </html>
  );
}
